project: default
source:
  repoURL: https://github.com/mrpommegit/gitea_helm.git
  path: Harshicorp_vault
  targetRevision: HEAD
destination:
  server: https://kubernetes.default.svc
  namespace: vault
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    enabled: true
  syncOptions:
    - CreateNamespace=true
