apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mrpommegit/gitea_helm.git
    targetRevision: main
    path: Harshicorp_vault
    helm:
      releaseName: vault
      valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
