vault:
  server:
    ha:
      enabled: false
    dataStorage:
      enabled: true
      size: 20Gi
    standalone:
      enabled: true
      config: |
        listener "tcp" {
          address         = "0.0.0.0:8200"
          cluster_address = "0.0.0.0:8201"
          tls_disable     = 1
        }

        storage "file" {
          path = "/vault/data"
        }

        ui = true
    ingress:
      enabled: true
      ingressClassName: public
      annotations: {}
      pathType: Prefix
      hosts:
        - host: vault.pi2security.com
          paths:
            - /
      tls:
        - secretName: vault-pi2security-com-tls
          hosts:
            - vault.pi2security.com
    service:
      type: ClusterIP
    readinessProbe:
      enabled: true
    livenessProbe:
      enabled: true

  ui:
    enabled: true
    serviceType: ClusterIP
    ingress:
      enabled: false

  injector:
    enabled: false

  csi:
    enabled: false
